version: "3.8"
services:
  registry:
    restart: always
    image: registry:2
    ports: 
      - "3001:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./registry:/var/lib/registry
